name: "${PROJECT_NAME:-programs}"
services:
  app:
    image: '692057070962.dkr.ecr.us-east-1.amazonaws.com/program-ids:${IMAGE_TAG:-latest}'
    env_file: .env
    ports:
      - '${WEB_PORT:-80}:8000'
    restart: unless-stopped
