services:
  laravel.test:
    image: 'sail-8.4/app'
    build:
      context: './vendor/laravel/sail/runtimes/8.4'
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    depends_on:
      - redis
    volumes:
      - .:/var/www/html
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    ports:
      - '${APP_PORT:-80}:80'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    networks:
      - sail
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  redis:
    image: 'redis:alpine'
    volumes:
      - sail-redis:/data
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
networks:
  sail:
    driver: bridge
volumes:
  sail-redis:
    driver: local
